# NEA Licensed Eating Establishments - Postal District Cleaning

This notebook cleans the NEA licensed eating establishments dataset and counts how
many licences fall into each Singapore postal district (D01-D28).

**How districts are decided.** Every Singapore 6-digit postal code starts with a
2-digit *postal sector*, and each sector belongs to exactly one of the 28 postal
districts. This sector-to-district table is the official definition used by URA, so
we use it as the main mapping. It is the only method the data fully supports, because
the dataset contains postal codes but no coordinates.

**Cross-check.** The `postal_district_boundaries_approx.geojson` file is an
*approximate* district map (its own notes say the shapes were built from URA planning
areas, not real postal sectors). We still use it as a spatial check: we geocode the
postal codes with OneMap, find which GeoJSON district each point falls in, and compare
that against the sector mapping to see how closely the approximate map agrees.

The final licence counts come from the sector mapping. The GeoJSON check is only used
to validate and to draw the map.

## 1. Import Libraries and Set File Paths

In [1]:
import re
import time

import pandas as pd
import requests
import geopandas as gpd
from shapely import make_valid
from pathlib import Path

In [2]:
project_folder = Path(r"C:\Users\euris\Documents\NYP\DPV Group Project")

raw_file_path = (
    project_folder
    / "Datasets"
    / "ListofNEALicensedEatingEstablishments.csv"
)

processed_folder_path = project_folder / "Processed Data"

geojson_path = (
    processed_folder_path
    / "postal_district_boundaries_approx.geojson"
)

final_output_path = (
    processed_folder_path
    / "nea_licences_by_postal_district.csv"
)

unmatched_output_path = (
    processed_folder_path
    / "nea_unmatched_records.csv"
)

removed_duplicates_path = (
    processed_folder_path
    / "nea_removed_duplicate_licences.csv"
)

geocode_cache_path = (
    processed_folder_path
    / "onemap_geocode_cache.csv"
)

address_cache_path = (
    processed_folder_path
    / "onemap_address_cache.csv"
)

disagreements_path = (
    processed_folder_path
    / "nea_geojson_vs_sector_disagreements.csv"
)

processed_folder_path.mkdir(parents=True, exist_ok=True)

print("Raw file exists:", raw_file_path.exists())
print("GeoJSON exists :", geojson_path.exists())
print("Output folder  :", processed_folder_path)

Raw file exists: True
GeoJSON exists : True
Output folder  : C:\Users\euris\Documents\NYP\DPV Group Project\Processed Data

## 2. Understand and Clean the Source Dataset

In [3]:
nea_raw = pd.read_csv(raw_file_path)

print("Number of rows and columns:", nea_raw.shape)
print("\nColumn names:", nea_raw.columns.tolist())
print("\nData types:")
print(nea_raw.dtypes)

nea_raw.head()

Number of rows and columns: (36687, 7)

Column names: ['licensee_name', 'licence_number', 'premises_address', 'grade', 'demerit_points', 'suspension_start_date', 'suspension_end_date']

Data types:
licensee_name            object
licence_number           object
premises_address         object
grade                    object
demerit_points           object
suspension_start_date    object
suspension_end_date      object
dtype: object

,licensee_name,licence_number,premises_address,grade,demerit_points,suspension_start_date,suspension_end_date
0,REPUBLIC HOTELS & RESORTS LIMITED,W99288X000,392 HAVELOCK ROAD (FISH/MEAT) GRAND COPTHORNE ...,A,na,na,na
1,REPUBLIC HOTELS & RESORTS LIMITED,W99281K000,392 HAVELOCK ROAD (BANQUET KITCHEN) GRAND COPT...,A,na,na,na
2,M.K. RAMA PTE LTD,W96344L000,37 NORRIS ROAD SINGAPORE 208279,A,na,na,na
3,GRAND PARK PROPERTY PTE. LTD.,W96230L000,10 COLEMAN STREET (2ND STOREY) GRAND PARK CITY...,A,na,na,na
4,MILLENIA PRIVATE LIMITED,W96214L000,2 TEMASEK BOULEVARD #B1-00 CONRAD CENTENNIAL S...,A,na,na,na

In [4]:
total_original_rows = len(nea_raw)

print("Total original rows:", total_original_rows)
print("\nBlank addresses:", (nea_raw["premises_address"].str.strip() == "").sum())
print("Missing licence numbers:", nea_raw["licence_number"].isnull().sum())

print("\nGrade values:", nea_raw["grade"].unique())
print("\n'na' text counts per column:")
print((nea_raw == "na").sum())

print("\nExact duplicate rows:", nea_raw.duplicated().sum())
print("Rows sharing a licence number:",
      nea_raw["licence_number"].duplicated().sum())
print("Rows sharing an address:",
      nea_raw["premises_address"].duplicated().sum())

Total original rows: 36687

Blank addresses: 0
Missing licence numbers: 0

Grade values: ['A' 'B' 'na' 'C']

'na' text counts per column:
licensee_name                0
licence_number               0
premises_address             0
grade                     5302
demerit_points           35083
suspension_start_date    36567
suspension_end_date      36567
dtype: int64

Exact duplicate rows: 5
Rows sharing a licence number: 46
Rows sharing an address: 14472

Many establishments share an address (a single building can hold many food stalls),
so shared addresses are normal and are **not** removed. We only remove rows that are
fully identical, and rows that repeat the same licence number.

In [5]:
nea = nea_raw.copy()

na_columns = [
    "grade",
    "demerit_points",
    "suspension_start_date",
    "suspension_end_date"
]

for column in na_columns:
    nea[column] = nea[column].replace("na", pd.NA)

nea["demerit_points"] = pd.to_numeric(
    nea["demerit_points"],
    errors="coerce"
)

print("Missing values after replacing 'na':")
print(nea[na_columns].isnull().sum())

Missing values after replacing 'na':
grade                     5302
demerit_points           35083
suspension_start_date    36567
suspension_end_date      36567
dtype: int64

In [6]:
nea = nea.drop_duplicates().reset_index(drop=True)
rows_after_exact_duplicates = len(nea)
exact_duplicates_removed = total_original_rows - rows_after_exact_duplicates

print("Exact duplicate rows removed:", exact_duplicates_removed)
print("Rows remaining:", rows_after_exact_duplicates)

Exact duplicate rows removed: 5
Rows remaining: 36682

Some licence numbers appear on more than one row. Checking the data, every repeated
licence number shares the **same premises address** (only the licensee name differs,
usually an ownership change). One licence number means one licence, so we keep the
first row for each licence number and save the removed rows for review.

In [7]:
duplicate_licence_rows = nea[
    nea["licence_number"].duplicated(keep=False)
].sort_values("licence_number")

duplicate_licence_rows.to_csv(removed_duplicates_path, index=False)

nea = nea.drop_duplicates(subset="licence_number").reset_index(drop=True)
unique_licences = len(nea)
duplicate_licences_removed = rows_after_exact_duplicates - unique_licences

print("Duplicate licence-number rows found:", len(duplicate_licence_rows))
print("Duplicate licence records removed:", duplicate_licences_removed)
print("Unique licences remaining:", unique_licences)

Duplicate licence-number rows found: 82
Duplicate licence records removed: 41
Unique licences remaining: 36641

In [8]:
postal_codes = nea["premises_address"].str.findall(r"\d{6}")

nea["postal_code"] = postal_codes.apply(
    lambda found: found[-1] if found else None
)

nea["postal_sector"] = nea["postal_code"].str[:2]

print("Licences with a 6-digit postal code:", nea["postal_code"].notnull().sum())
print("Licences with no postal code in the address:",
      nea["postal_code"].isnull().sum())

nea[["premises_address", "postal_code", "postal_sector"]].head()

Licences with a 6-digit postal code: 30568
Licences with no postal code in the address: 6073

                                    premises_address postal_code postal_sector
0  392 HAVELOCK ROAD (FISH/MEAT) GRAND COPTHORNE ...      169663            16
1  392 HAVELOCK ROAD (BANQUET KITCHEN) GRAND COPT...      169663            16
2                    37 NORRIS ROAD SINGAPORE 208279      208279            20
3  10 COLEMAN STREET (2ND STOREY) GRAND PARK CITY...      179809            17
4  2 TEMASEK BOULEVARD #B1-00 CONRAD CENTENNIAL S...      038982            03

## 3. Inspect and Prepare the GeoJSON

In [9]:
districts = gpd.read_file(geojson_path)

print("Number of districts:", len(districts))
print("Coordinate reference system:", districts.crs)
print("\nGeometry types:")
print(districts.geometry.geom_type.value_counts())
print("\nColumns:", districts.columns.tolist())

districts[["postal_district", "postal_district_name"]].head()

Number of districts: 28
Coordinate reference system: EPSG:4326

Geometry types:
Polygon         21
MultiPolygon     7
Name: count, dtype: int64

Columns: ['postal_district_number', 'postal_district', 'postal_district_name', 'postal_district_label', 'planning_area_count', 'planning_areas', 'source_regions', 'mapping_method', 'geometry']

  postal_district                               postal_district_name
0             D01        Raffles Place, Cecil, Marina, People's Park
1             D02                               Anson, Tanjong Pagar
2             D03                            Queenstown, Tiong Bahru
3             D04                        Telok Blangah, Harbourfront
4             D05  Pasir Panjang, Hong Leong Garden, Clementi New...

In [10]:
print("Invalid geometries:", (~districts.geometry.is_valid).sum())
print("Missing geometries:", districts.geometry.isnull().sum())
print("Empty geometries:", districts.geometry.is_empty.sum())

districts["geometry"] = districts["geometry"].apply(make_valid)

if districts.crs is None:
    districts = districts.set_crs("EPSG:4326")
else:
    districts = districts.to_crs("EPSG:4326")

print("\nInvalid geometries after repair:", (~districts.geometry.is_valid).sum())

expected_districts = [f"D{number:02d}" for number in range(1, 29)]
geojson_districts = sorted(districts["postal_district"])

print("\nGeoJSON has all D01-D28:", geojson_districts == expected_districts)
print("Unexpected labels:",
      sorted(set(geojson_districts) - set(expected_districts)))

Invalid geometries: 0
Missing geometries: 0
Empty geometries: 0

Invalid geometries after repair: 0

GeoJSON has all D01-D28: True
Unexpected labels: []

## 4. Map Establishments to Postal Districts

The table below is the official URA sector-to-district mapping. It was verified
against URA's published list and Wikipedia's postal-code article. The first two digits
of a postal code give the sector; the sector gives the district.

In [11]:
district_sectors = {
    "D01": ["01", "02", "03", "04", "05", "06"],
    "D02": ["07", "08"],
    "D03": ["14", "15", "16"],
    "D04": ["09", "10"],
    "D05": ["11", "12", "13"],
    "D06": ["17"],
    "D07": ["18", "19"],
    "D08": ["20", "21"],
    "D09": ["22", "23"],
    "D10": ["24", "25", "26", "27"],
    "D11": ["28", "29", "30"],
    "D12": ["31", "32", "33"],
    "D13": ["34", "35", "36", "37"],
    "D14": ["38", "39", "40", "41"],
    "D15": ["42", "43", "44", "45"],
    "D16": ["46", "47", "48"],
    "D17": ["49", "50", "81"],
    "D18": ["51", "52"],
    "D19": ["53", "54", "55", "82"],
    "D20": ["56", "57"],
    "D21": ["58", "59"],
    "D22": ["60", "61", "62", "63", "64"],
    "D23": ["65", "66", "67", "68"],
    "D24": ["69", "70", "71"],
    "D25": ["72", "73"],
    "D26": ["77", "78"],
    "D27": ["75", "76"],
    "D28": ["79", "80"]
}

sector_to_district = {}
for district, sectors in district_sectors.items():
    for sector in sectors:
        sector_to_district[sector] = district

print("Sectors covered by the district table:", len(sector_to_district))

Sectors covered by the district table: 81

In [12]:
nea["postal_district"] = nea["postal_sector"].map(sector_to_district)

matched = nea[nea["postal_district"].notnull()].copy()
unmatched = nea[nea["postal_district"].isnull()].copy()

print("Matched to a district:", len(matched))
print("Unmatched:", len(unmatched))
print("Matched + unmatched equals cleaned rows:",
      len(matched) + len(unmatched) == unique_licences)

Matched to a district: 30558
Unmatched: 6083
Matched + unmatched equals cleaned rows: True

In [13]:
no_postal_code = unmatched["postal_code"].isnull().sum()
unknown_sector = unmatched["postal_code"].notnull().sum()

print("Unmatched because there is no postal code:", no_postal_code)
print("Unmatched because the sector is outside D01-D28:", unknown_sector)
print("Unknown sectors seen:",
      sorted(unmatched.loc[unmatched["postal_code"].notnull(), "postal_sector"].unique()))

unmatched[["premises_address", "postal_code", "postal_sector"]].head()

Unmatched because there is no postal code: 6073
Unmatched because the sector is outside D01-D28: 10
Unknown sectors seen: ['90']

,premises_address,postal_code,postal_sector
629,CHOA CHU KANG PARK CHOA CHU KANG DRIVE,None,None
1117,101 MOUNT FABER PARK KIOSK FABER POINT,None,None
1625,391 ORCHARD ROAD #04-20A/21TAKASHIMAYA SHOPPIN...,None,None
1912,2 STAMFORD ROADLEVEL 68 & 69EQUINOX RESTAURANT,None,None
1940,6 RAFFLES BLVD 4TH STOREY MARINA MANDARIN,None,None

## 5. Recover Missing Districts by Address Lookup (OneMap)

Some addresses have no postal code, so the sector mapping cannot place them. For
those rows we ask OneMap to look up the address text and return a postal code, then map
that code to a district with the same sector table above. Results are cached, so this
only runs once. Addresses OneMap cannot resolve are left unmatched.

In [14]:
onemap_token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOTcyMSwiZm9yZXZlciI6ZmFsc2UsImlzcyI6Ik9uZU1hcCIsImlhdCI6MTc4NDQ0MTEwMiwibmJmIjoxNzg0NDQxMTAyLCJleHAiOjE3ODQ3MDAzMDIsImp0aSI6IjczOTdjYTYwLTcyMTEtNDE1My04YTFiLWZmM2E2ZWY3NzI0OSJ9.3yc4djhmkW4G0AKrQL8TQPncozztpxsb1FsCDBwiqXuSpzbdql6XpYjIr9URNRZBGZ7uj5WEWCLKe2qiEiIkWPPdXsJJ7tsPxe2rV8ws3mq--urEP6CiNskmznVtClTI6FZQSC5JBikD-GLAhRPNEM2bjaLBIaIUSVBA72IfImgUwX2bocO2tQjTjz3f9Tph36ia_UeM-DyhZjjRjv080L4tmzDeGPRNtadxzzAmGhO5-ZClf-21vb2aNB6g1S0RRy5jyT0qo6TrIlLBPzxEE74pzLtVcgnsSED5v88Te3giRsDMiWV81dQcnSxAitqStjxX1OZtroAxdsPIasBBXw"


def clean_address_for_search(address):
    text = re.sub(r"\(.*?\)", " ", address)
    text = re.sub(r"#\S+", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def lookup_postal_code(address):
    url = "https://www.onemap.gov.sg/api/common/elastic/search"
    params = {
        "searchVal": clean_address_for_search(address),
        "returnGeom": "Y",
        "getAddrDetails": "Y",
        "pageNum": 1
    }
    headers = {"Authorization": onemap_token}

    try:
        response = requests.get(url, params=params, headers=headers, timeout=20)
        results = response.json().get("results", [])
        if results:
            postal = str(results[0].get("POSTAL", ""))
            if postal.isdigit() and len(postal) == 6:
                return postal
    except Exception:
        pass

    return None

In [15]:
from concurrent.futures import ThreadPoolExecutor
from threading import Lock

addresses_without_code = sorted(
    nea.loc[
        nea["postal_code"].isnull(),
        "premises_address"
    ].dropna().unique()
)

if address_cache_path.exists():
    address_cache = pd.read_csv(address_cache_path, dtype=str)
else:
    address_cache = pd.DataFrame(
        columns=["premises_address", "postal_code"]
    )

address_cache = address_cache.drop_duplicates(
    subset="premises_address",
    keep="last"
)

already_looked_up = set(
    address_cache["premises_address"].dropna()
)

addresses_to_lookup = [
    address for address in addresses_without_code
    if address not in already_looked_up
]

print("Addresses with no postal code:", len(addresses_without_code))
print("Already in cache:", len(already_looked_up))
print("Need to look up now:", len(addresses_to_lookup))

request_lock = Lock()
last_request_time = [0.0]
minimum_request_interval = 0.22


def lookup_one_address(address):
    with request_lock:
        time_since_last_request = (
            time.monotonic() - last_request_time[0]
        )

        remaining_wait_time = (
            minimum_request_interval - time_since_last_request
        )

        if remaining_wait_time > 0:
            time.sleep(remaining_wait_time)

        last_request_time[0] = time.monotonic()

    return {
        "premises_address": address,
        "postal_code": lookup_postal_code(address)
    }


new_lookups = []

with ThreadPoolExecutor(max_workers=3) as executor:
    lookup_results = executor.map(
        lookup_one_address,
        addresses_to_lookup
    )

    for count, result in enumerate(lookup_results, start=1):
        new_lookups.append(result)

        if count % 50 == 0:
            print(
                "Looked up",
                count,
                "of",
                len(addresses_to_lookup)
            )

        if count % 200 == 0:
            address_cache = pd.concat(
                [address_cache, pd.DataFrame(new_lookups)],
                ignore_index=True
            )

            address_cache.to_csv(
                address_cache_path,
                index=False
            )

            new_lookups = []


if len(new_lookups) > 0:
    address_cache = pd.concat(
        [address_cache, pd.DataFrame(new_lookups)],
        ignore_index=True
    )

address_cache = address_cache.drop_duplicates(
    subset="premises_address",
    keep="last"
)

address_cache.to_csv(
    address_cache_path,
    index=False
)

print(
    "\nAddresses OneMap found a postal code for:",
    address_cache["postal_code"].notnull().sum()
)

Addresses with no postal code: 6053
Already in cache: 4400
Need to look up now: 1653
Looked up 50 of 1653
Looked up 100 of 1653
Looked up 150 of 1653
Looked up 200 of 1653
Looked up 250 of 1653
Looked up 300 of 1653
Looked up 350 of 1653
Looked up 400 of 1653
Looked up 450 of 1653
Looked up 500 of 1653
Looked up 550 of 1653
Looked up 600 of 1653
Looked up 650 of 1653
Looked up 700 of 1653
Looked up 750 of 1653
Looked up 800 of 1653
Looked up 850 of 1653
Looked up 900 of 1653
Looked up 950 of 1653
Looked up 1000 of 1653
Looked up 1050 of 1653
Looked up 1100 of 1653
Looked up 1150 of 1653
Looked up 1200 of 1653
Looked up 1250 of 1653
Looked up 1300 of 1653
Looked up 1350 of 1653
Looked up 1400 of 1653
Looked up 1450 of 1653
Looked up 1500 of 1653
Looked up 1550 of 1653
Looked up 1600 of 1653
Looked up 1650 of 1653

Addresses OneMap found a postal code for: 5

In [16]:
matched_before_lookup = nea["postal_district"].notnull().sum()

found_codes = address_cache.dropna(subset=["postal_code"])
address_to_postal = dict(zip(
    found_codes["premises_address"],
    found_codes["postal_code"]
))

missing_code = nea["postal_code"].isnull()
nea.loc[missing_code, "postal_code"] = (
    nea.loc[missing_code, "premises_address"].map(address_to_postal)
)

nea["postal_sector"] = nea["postal_code"].str[:2]
nea["postal_district"] = nea["postal_sector"].map(sector_to_district)

matched = nea[nea["postal_district"].notnull()].copy()
unmatched = nea[nea["postal_district"].isnull()].copy()

recovered_by_lookup = int(nea["postal_district"].notnull().sum() - matched_before_lookup)
no_postal_code = unmatched["postal_code"].isnull().sum()
unknown_sector = unmatched["postal_code"].notnull().sum()

print("Districts recovered by address lookup:", recovered_by_lookup)
print("Matched after recovery:", len(matched))
print("Still unmatched:", len(unmatched))
print("  - still no postal code:", no_postal_code)
print("  - sector outside D01-D28:", unknown_sector)

Districts recovered by address lookup: 5
Matched after recovery: 30563
Still unmatched: 6078
  - still no postal code: 6068
  - sector outside D01-D28: 10

## 6. Validate the Mapping (OneMap and GeoJSON cross-check)

We geocode each unique postal code with OneMap to get its latitude and longitude,
find which GeoJSON district the point falls inside, and compare that with the sector
mapping. Results are cached to a file, so the slow geocoding only happens on the first
run. It reuses the `onemap_token` set in the previous section, and the search endpoint
also works without a token if it has expired (renew it free at onemap.gov.sg).

In [17]:
def geocode_postal_code(postal_code):
    url = "https://www.onemap.gov.sg/api/common/elastic/search"
    params = {
        "searchVal": postal_code,
        "returnGeom": "Y",
        "getAddrDetails": "Y",
        "pageNum": 1
    }
    headers = {"Authorization": onemap_token}

    try:
        response = requests.get(url, params=params, headers=headers, timeout=20)
        results = response.json().get("results", [])
        if results:
            first = results[0]
            return float(first["LATITUDE"]), float(first["LONGITUDE"])
    except Exception:
        pass

    return None, None

In [18]:
unique_postal_codes = sorted(nea["postal_code"].dropna().unique())

if geocode_cache_path.exists():
    geocode_cache = pd.read_csv(geocode_cache_path, dtype={"postal_code": str})
else:
    geocode_cache = pd.DataFrame(columns=["postal_code", "latitude", "longitude"])

already_geocoded = set(geocode_cache["postal_code"])
codes_to_lookup = [code for code in unique_postal_codes if code not in already_geocoded]

print("Unique postal codes:", len(unique_postal_codes))
print("Already in cache:", len(already_geocoded))
print("Need to geocode now:", len(codes_to_lookup))

new_results = []
for count, code in enumerate(codes_to_lookup, start=1):
    latitude, longitude = geocode_postal_code(code)
    new_results.append({
        "postal_code": code,
        "latitude": latitude,
        "longitude": longitude
    })
    time.sleep(0.2)

    if count % 200 == 0:
        print("Geocoded", count, "of", len(codes_to_lookup))
        saved = pd.concat([geocode_cache, pd.DataFrame(new_results)], ignore_index=True)
        saved.to_csv(geocode_cache_path, index=False)

geocode_cache = pd.concat([geocode_cache, pd.DataFrame(new_results)], ignore_index=True)
geocode_cache["postal_code"] = geocode_cache["postal_code"].astype(str).str.zfill(6)
geocode_cache.to_csv(geocode_cache_path, index=False)

geocoded_ok = geocode_cache.dropna(subset=["latitude", "longitude"])
print("\nPostal codes with coordinates:", len(geocoded_ok))
print("Postal codes OneMap could not locate:",
      len(geocode_cache) - len(geocoded_ok))

Unique postal codes: 6546
Already in cache: 0
Need to geocode now: 6546
Geocoded 200 of 6546

C:\Users\euris\AppData\Local\Temp\ipykernel_36068\389911999.py:27: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  saved = pd.concat([geocode_cache, pd.DataFrame(new_results)], ignore_index=True)

Geocoded 400 of 6546
Geocoded 600 of 6546
Geocoded 800 of 6546
Geocoded 1000 of 6546
Geocoded 1200 of 6546
Geocoded 1400 of 6546
Geocoded 1600 of 6546
Geocoded 1800 of 6546
Geocoded 2000 of 6546
Geocoded 2200 of 6546
Geocoded 2400 of 6546
Geocoded 2600 of 6546
Geocoded 2800 of 6546
Geocoded 3000 of 6546
Geocoded 3200 of 6546
Geocoded 3400 of 6546
Geocoded 3600 of 6546
Geocoded 3800 of 6546
Geocoded 4000 of 6546
Geocoded 4200 of 6546
Geocoded 4400 of 6546
Geocoded 4600 of 6546
Geocoded 4800 of 6546
Geocoded 5000 of 6546
Geocoded 5200 of 6546
Geocoded 5400 of 6546
Geocoded 5600 of 6546
Geocoded 5800 of 6546
Geocoded 6000 of 6546
Geocoded 6200 of 6546
Geocoded 6400 of 6546

Postal codes with coordinates: 6313
Postal codes OneMap could not locate: 233

C:\Users\euris\AppData\Local\Temp\ipykernel_36068\389911999.py:30: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  geocode_cache = pd.concat([geocode_cache, pd.DataFrame(new_results)], ignore_index=True)

In [19]:
located = geocode_cache.dropna(subset=["latitude", "longitude"]).copy()

points = gpd.GeoDataFrame(
    located,
    geometry=gpd.points_from_xy(located["longitude"], located["latitude"]),
    crs="EPSG:4326"
)

joined = gpd.sjoin(
    points,
    districts[["postal_district", "geometry"]],
    predicate="within",
    how="left"
)

points_in_two_districts = joined.index.duplicated().sum()
joined = joined[~joined.index.duplicated(keep="first")]
points_outside_all = joined["postal_district"].isnull().sum()

print("Points that fell inside two districts (kept first):", points_in_two_districts)
print("Points that fell outside every district:", points_outside_all)

code_to_geojson_district = joined[["postal_code", "postal_district"]].rename(
    columns={"postal_district": "geojson_district"}
)

Points that fell inside two districts (kept first): 0
Points that fell outside every district: 2

In [20]:
check = matched.merge(code_to_geojson_district, on="postal_code", how="left")

comparable = check.dropna(subset=["geojson_district"])
agreement = (comparable["postal_district"] == comparable["geojson_district"]).mean()

disagreements = comparable[
    comparable["postal_district"] != comparable["geojson_district"]
]

disagreements[[
    "premises_address",
    "postal_code",
    "postal_district",
    "geojson_district"
]].to_csv(disagreements_path, index=False)

print("Licences comparable (sector district and GeoJSON district both known):",
      len(comparable))
print("Agreement between sector mapping and GeoJSON:",
      f"{agreement:.1%}")
print("Disagreements saved for review:", len(disagreements))

Licences comparable (sector district and GeoJSON district both known): 29724
Agreement between sector mapping and GeoJSON: 73.3%
Disagreements saved for review: 7927

A high agreement means the approximate GeoJSON map lines up well with the official
sector districts. Any disagreements are usually near district boundaries, where the
approximate shapes differ from the true postal sectors. Because the sector table is the
official definition, the final counts follow it, not the GeoJSON.

## 7. Create and Save the Final Output

In [21]:
licence_counts = matched["postal_district"].value_counts()

final_output = pd.DataFrame({
    "Postal District": expected_districts,
    "Number of Licences": [int(licence_counts.get(d, 0)) for d in expected_districts]
})

final_output = final_output.sort_values("Postal District").reset_index(drop=True)

final_output.to_csv(final_output_path, index=False)

unmatched_review = unmatched[[
    "licensee_name",
    "licence_number",
    "premises_address",
    "postal_code",
    "postal_sector"
]].copy()

unmatched_review["reason"] = unmatched_review["postal_code"].apply(
    lambda code: "no postal code in address" if pd.isnull(code)
    else "postal sector outside D01-D28 (offshore or special)"
)

unmatched_review.to_csv(unmatched_output_path, index=False)

print("Saved final output to:", final_output_path)
print("Saved unmatched records to:", unmatched_output_path)

final_output

Saved final output to: C:\Users\euris\Documents\NYP\DPV Group Project\Processed Data\nea_licences_by_postal_district.csv
Saved unmatched records to: C:\Users\euris\Documents\NYP\DPV Group Project\Processed Data\nea_unmatched_records.csv

   Postal District  Number of Licences
0              D01                1990
1              D02                 570
2              D03                 971
3              D04                 782
4              D05                1594
5              D06                 408
6              D07                1169
7              D08                 799
8              D09                1593
9              D10                 607
10             D11                 473
11             D12                1103
12             D13                 501
13             D14                1677
14             D15                 995
15             D16                1339
16             D17                 555
17             D18                1560
18             D19                2353
19             D20                1660
20             D21                 314
21             D22                2947
22             D23                1622
23             D24                  45
24             D25                1258
25             D26                  65
26             D27                1405
27             D28                 208

## 8. Final Processing Summary

In [22]:
matched_licences = len(matched)
final_total = int(final_output["Number of Licences"].sum())

print("Total original rows           :", total_original_rows)
print("Exact duplicate rows removed  :", exact_duplicates_removed)
print("Duplicate licence rows removed:", duplicate_licences_removed)
print("Unique licences (cleaned)     :", unique_licences)
print("Recovered by address lookup   :", recovered_by_lookup)
print("Matched to a district         :", matched_licences)
print("Unmatched                     :", len(unmatched))
print("  - no postal code            :", no_postal_code)
print("  - sector outside D01-D28    :", unknown_sector)
print("Final total licences counted  :", final_total)
print()
print("Reconciliation checks")
print("  matched + unmatched == cleaned :",
      matched_licences + len(unmatched) == unique_licences)
print("  final total == matched         :",
      final_total == matched_licences)
print("  GeoJSON agreement              :", f"{agreement:.1%}")

Total original rows           : 36687
Exact duplicate rows removed  : 5
Duplicate licence rows removed: 41
Unique licences (cleaned)     : 36641
Recovered by address lookup   : 5
Matched to a district         : 30563
Unmatched                     : 6078
  - no postal code            : 6068
  - sector outside D01-D28    : 10
Final total licences counted  : 30563

Reconciliation checks
  matched + unmatched == cleaned : True
  final total == matched         : True
  GeoJSON agreement              : 73.3%

### Notes and limitations

- Districts are assigned from the **postal sector** (first two digits of the postal
  code), which is the official URA definition. This is the most reliable method the
  data supports, since the dataset has postal codes but no coordinates.
- **Address-lookup recovery.** Rows with no postal code get a second pass: OneMap looks
  up the address text and, when it returns a valid postal code, that code is mapped to a
  district. This recovers many parks, construction sites, and buildings named only by
  road. It runs after the main mapping, so recovered licences are included in the counts.
- **Unmatched licences are not counted.** After recovery, the rows that remain unmatched
  are addresses OneMap still could not resolve, or offshore postal sectors such as 90
  (Pulau Bukom) that are outside the 28 mainland districts. All unmatched rows are saved
  to `nea_unmatched_records.csv` for review.
- The GeoJSON is an **approximate** district map built from planning areas, so it is
  used only as a cross-check and for drawing, not for the final counts. The agreement
  figure above shows how closely it matches the official sector districts.
- OneMap may fail to locate a few postal codes (very new or unusual buildings). Those
  points are simply left out of the cross-check and do not affect the final counts.