# Data Understanding

remove later:

order of sorting

1. rental analysis
2. geo map
3. nea list
4. population
5. mrt map

In [6]:
# import required libraries

import pandas as pd
from pathlib import Path
#import geopandas as gpd

In [7]:
# import the datasets

dataset_path = Path('Datasets')

# dataset paths

rental_dataset_path = dataset_path / 'CommercialRetailRentalAnalysis20260629170349.csv'
geo_dataset_path = dataset_path / 'MasterPlan2019PlanningAreaBoundaryNoSea.geojson'
nea_license_dataset_path = dataset_path / 'ListofNEALicensedEatingEstablishments.csv'
population_dataset_path = dataset_path / 'ResidentPopulationbyPlanningAreaSubzoneofResidenceandTypeofDwellingCensusofPopulation2020.csv'
mrt_traffic_dataset_path = dataset_path / 'origin_destination_train_202605.csv'



# datasets

rental_dataset = pd.read_csv(rental_dataset_path)
#geo_dataset = pd.read_csv(geo_dataset_path)
nea_license_dataset = pd.read_csv(nea_license_dataset_path)
population_dataset = pd.read_csv(population_dataset_path)
mrt_traffic_dataset = pd.read_csv(mrt_traffic_dataset_path)

## Commerical Retail Rental Dataset

In [8]:
rental_dataset.head()

,Postal District,Floor Level,Floor Area (SQM),25th Percentile ($ PSM),Median ($PSM),75th Percentile ($PSM),Reference Period
0,1,B1 & Below,30 & Below,69.89,70.20,112.70,2021Q1
1,1,B1 & Below,>30 - 100,65.45,87.61,98.41,2021Q1
2,1,B1 & Below,>100 - 300,50.33,57.70,87.20,2021Q1
3,1,Level 1,30 & Below,87.36,123.94,222.00,2021Q1
4,1,Level 1,>30 - 100,75.26,109.37,147.04,2021Q1

## Geo Dataset

## NEA Licensed Eating Establishments Dataset

In [9]:
nea_license_dataset.head()

,licensee_name,licence_number,premises_address,grade,demerit_points,suspension_start_date,suspension_end_date
0,REPUBLIC HOTELS & RESORTS LIMITED,W99288X000,392 HAVELOCK ROAD (FISH/MEAT) GRAND COPTHORNE ...,A,na,na,na
1,REPUBLIC HOTELS & RESORTS LIMITED,W99281K000,392 HAVELOCK ROAD (BANQUET KITCHEN) GRAND COPT...,A,na,na,na
2,M.K. RAMA PTE LTD,W96344L000,37 NORRIS ROAD SINGAPORE 208279,A,na,na,na
3,GRAND PARK PROPERTY PTE. LTD.,W96230L000,10 COLEMAN STREET (2ND STOREY) GRAND PARK CITY...,A,na,na,na
4,MILLENIA PRIVATE LIMITED,W96214L000,2 TEMASEK BOULEVARD #B1-00 CONRAD CENTENNIAL S...,A,na,na,na

## Population by Planning Area Subzone Dataset

In [10]:
population_dataset.head()

,Number,Total,HDBDwellings_Total,HDBDwellings_1_and2_RoomFlats1,HDBDwellings_3_RoomFlats,HDBDwellings_4_RoomFlats,HDBDwellings_5_RoomandExecutiveFlats,CondominiumsandOtherApartments,LandedProperties,Others
0,Total,4044210,3152410,177360,575200,1338370,1061480,607940,248860,35000
1,Ang Mo Kio - Total,162280,131020,10720,55910,43030,21370,13980,15880,1390
2,Ang Mo Kio Town Centre,4810,2830,-,400,630,1800,1950,-,30
3,Cheng San,28070,27970,970,13290,8810,4900,-,-,100
4,Chong Boon,26500,26000,1470,12180,8560,3790,-,-,500

## MRT Traffic by station code dataset

In [11]:
mrt_traffic_dataset.head()

,YEAR_MONTH,DAY_TYPE,TIME_PER_HOUR,PT_TYPE,ORIGIN_PT_CODE,DESTINATION_PT_CODE,TOTAL_TRIPS
0,2026-05,WEEKENDS/HOLIDAY,19,TRAIN,EW28,CC17/TE9,16
1,2026-05,WEEKDAY,9,TRAIN,PW3,EW1,1
2,2026-05,WEEKDAY,20,TRAIN,PW4,CC27,4
3,2026-05,WEEKENDS/HOLIDAY,11,TRAIN,TE24,CC10/DT26,1
4,2026-05,WEEKENDS/HOLIDAY,16,TRAIN,TE4,DT22,1

# Data Cleaning

## Commerical Retail Rental Dataset

In [13]:
# check for missing values

rental_dataset.isnull().sum()

Postal District            0
Floor Level                0
Floor Area (SQM)           0
25th Percentile ($ PSM)    0
Median ($PSM)              0
75th Percentile ($PSM)     0
Reference Period           0
dtype: int64

In [15]:
# remove missing values

rental_dataset.dropna()

rental_dataset.head()

,Postal District,Floor Level,Floor Area (SQM),25th Percentile ($ PSM),Median ($PSM),75th Percentile ($PSM),Reference Period
0,1,B1 & Below,30 & Below,69.89,70.20,112.70,2021Q1
1,1,B1 & Below,>30 - 100,65.45,87.61,98.41,2021Q1
2,1,B1 & Below,>100 - 300,50.33,57.70,87.20,2021Q1
3,1,Level 1,30 & Below,87.36,123.94,222.00,2021Q1
4,1,Level 1,>30 - 100,75.26,109.37,147.04,2021Q1

## Geo Dataset

## NEA Licensed Eating Establishments Dataset

## Population by Planning Area Subzone Dataset

## MRT Traffic by station code dataset

# Data Preparation

## Commerical Retail Rental Dataset

## Geo Dataset

## NEA Licensed Eating Establishments Dataset

## Population by Planning Area Subzone Dataset

## MRT Traffic by station code dataset